"""word2number table

Revision ID: 95fd321929cb
Revises: 
Create Date: 2021-07-04 13:13:17.182326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95fd321929cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word2number',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encoded', sa.String(length=2000), nullable=True),
    sa.Column('path', sa.String(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word2number')
    # ### end Alembic commands ###
