"""empty message

Revision ID: de31ce119b18
Revises: 95fd321929cb
Create Date: 2021-07-04 13:24:42.679114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de31ce119b18'
down_revision = '95fd321929cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word2numbers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encoded', sa.String(length=2000), nullable=True),
    sa.Column('path', sa.String(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('word2number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word2number',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('encoded', sa.VARCHAR(length=2000), autoincrement=False, nullable=True),
    sa.Column('path', sa.VARCHAR(length=4000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='word2number_pkey')
    )
    op.drop_table('word2numbers')
    # ### end Alembic commands ###
