name: Run Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          pip install ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: False

      - name: Install geerlingguy.pip
        run: |
          ansible-galaxy install geerlingguy.pip

      - name: Install singleplatform-eng.users
        run: |
          ansible-galaxy install singleplatform-eng.users

      - name: Install OpenVPN
        run: |
          sudo apt install -y openvpn openvpn-systemd-resolved

      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          config_file: .github/workflows/client.ovpn
          tls_auth_key: ${{ secrets.tls }}

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory/inventory.ini copy_files.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: False  # Opcjonalnie, wyłącza sprawdzanie host key
        working-directory: .  # Opcjonalnie, ustaw katalog, w którym znajduje się playbook i plik inventory
