name: Run Ansible Playbook

on:
  push:
    branches:
      - main  # Dostosuj do swojej głównej gałęzi

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          pip install ansible
        env:
          ANSIBLE_HOST_KEY_CHECKING: False  # Opcjonalnie, wyłącza sprawdzanie host key

      - name: Install aptitude
        run: |
          apt-get install aptitude

      - name: 

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory/inventory.ini copy_files.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: False  # Opcjonalnie, wyłącza sprawdzanie host key
        working-directory: .  # Opcjonalnie, ustaw katalog, w którym znajduje się playbook i plik inventory
